"""Added logged out field

Revision ID: d0f0a0af3c33
Revises: 57e34fe9944f
Create Date: 2026-05-31 22:36:39.777921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f0a0af3c33'
down_revision: Union[str, Sequence[str], None] = '57e34fe9944f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('logged_out_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'logged_out_at')
    # ### end Alembic commands ###
